### ISSUE TITLE
ebpf

### ISSUE THREAD

**Issue by mz649** [feicong/android_ebpf#1]
大佬，问一下你这真机的内核版本是多少，好像android_ebpf要内核5.0以上的

**Comment by mz649** [comment]
> 我测试的4.14 安卓10 arm64内核，自己打了补丁了

之前我也想尝试写ebpf 来记录系统调用 不过没能实现出来，我内核版本4.4

**Comment by feicong** [comment]
你可以参考这篇的方法，自己打下补丁： https://blog.seeflower.dev/archives/139/

**Comment by mz649** [comment]
> 你可以参考这篇的方法，自己打下补丁： https://blog.seeflower.dev/archives/139/

非常感谢大佬的回复，我去尝试一下
